import { createContext } from 'react'

export const GeneratedVaribles = createContext({
    autoGenerated: {},
    setautoGenerated: {},
    externalUser: {},
    externalBaseUrl: {},
    allOptionSets: {},
    setallOptionSets: {},
    order: {},
    setOrder: {},
    orderBy: {},
    setOrderBy: {},
    reloadData: {},
    setreloadData: {},
    setselectRows: {},
    selectRows: {},
    setprograms: {},
    programs: {},
    userOrgUnit: {},
    tEItransfered: {},
    setTEItransfered: {},
    allTeisFormated: {},
    setallTeisFormated: {},
    enrollmentDate: {},
    setEnrollmentDate: {},
    attributeFilters: {},
    setattributeFilters: {}
})

